name: Hello World GHA
on: workflow_dispatch
jobs:
  job01:
    runs-on: ubuntu-24.04
    steps:
      - name: Imprime Saudação
        run: echo "Olá Mundo Véi de Guerra!"
      - name: Termina HW
        run: echo "É isso aí... Terminou!"
